"""Freeze repository-agent interpretation before independent Gate C."""
import json
from pathlib import Path
import replay as r
OUT=r.OUT

def main():
 s=r.load(OUT/'SUMMARY.json');norm=r.load(OUT/'scoring_recovery/SUMMARY.json');f=r.load(OUT/'followup_macro_mode/SUMMARY.json')
 body='''# Completed primary interpretation before Gate C

This is the repository-agent interpretation, frozen before independent post-replay review. Original history remains immutable. No model treatment, agent trajectory, product runtime edit, semantic repair, verifier revival, or new agent-facing derived diagnostic occurred.

Preregistered primary P1:183 archived ordinary controls/98 tasks; all183 original numeric tuples reproduced, zero missing formula caches,142 scorable pairs,0 cache-only gains,141 no material effect,1 harm,41 unresolved. All41 Template submissions resolve with no material effect. Unresolved bounds0–22.40% runs/0–21.43% tasks prevent a global-zero claim. No A/B task-materiality threshold is met. The retained ordinary archive pipeline explicitly stages raw outputs then refreshes with LibreOffice before official scoring; every archived/raw P1 hash differs. Current source plus hashes/caches/numeric compatibility support stage separation, not proof that every old transformation was exclusively recalc.

P2:191 research outputs/60 tasks;163 valid pairs,46 cache-only recoveries/21 tasks (45 Template/20 tasks,1 Debugging),65 ambiguous gains,17 harms,35 no material effect,28 unresolved. Formula identity:33 raw identical,99 semantic identical,31 changed,28 undetermined. Strong cases:1 raw-byte-identical V0→V1,45 semantic/package-changed; all witnesses preserve V0 raw formulas and match complete assessed typed/formula/color surfaces. Seven exact strong gains,45 modification gains,one regression-only error/formula-fallback gain; fallback is official recovery, not numerical correctness. Never count all123 modification improvements or17 total exact improvements as cache-proven. P2 excluding discovery:39/168 strong/14 tasks.

Only9 P2 strong cases have archived submission bytes and original numeric reproduction:7 Phase12 CONTROL and2 candidate-checkpoint submissions. Three exact failures resolve; six remain failures with component gains.37 strong current candidate gains lack archival historical proof.160/191 P2 files are run-local byte-unverified; historical numeric coincidence does not establish bytes. The retained task-specific report/failure-tag audit found no explicit semantic/model-failure attribution for those9; general report links do not refute an architectural diagnosis. Qualify score meaning, not entire remaining failures or unlinked reports. Historical scorer implementation identities remain unavailable.

Regressions remain: primary P1 Financial_Model:14_05 mod−.1129/reg−.0129; P2 17 material harms, including mixed gains. GateB inspected two harms and found genuine expected-blank gold cells, with formulas already in V0 becoming visible after recalc. Do not misdescribe these as stale golden formula caches or infer all harms came from LO formula damage. Harm branch lacks sufficiency witnesses; attribution remains recalc-associated. No golden refresh/new treatment needed or run.

P3 is historical context, never pooled:848 rows/297 tasks,792 confirmed structured+56older noncontrol/unknown. First-pass403 technical clone-error rows were separately normalized using identical V0/existing V1/input/golden/scorer bytes; first-pass RAW/SUMMARY remain frozen. Lossless nested DimensionHolder reducer and native score/count parity passed; all remaining newly assessable gains escalate to the frozen full witness/classifier. This is scoring execution normalization, not another workbook causal intervention. Normalized results follow below; unknown architecture claims are not automatically rewritten.

Proposed verdicts: C — CACHE EFFECT EXISTS BUT DOES NOT MATERIALLY ALTER BASELINE for the preregistered archived ordinary control population. The effect clearly extends to newer research raw-output endpoints, especially Template; C must not be read as absence of that effect or absence in unresolved/unretained controls. Historical evidence: SELECTIVE HISTORICAL REINTERPRETATION REQUIRED for verified score boundaries and unequal-refresh endpoints, not wholesale architecture repudiation. Scaffold: ADD RECALC BEFORE EVALUATION ONLY. Evaluator: YES — REQUIRED FOR REFERENCE-FAIR EVALUATION in a compatible, declared supported formula/engine domain; preserve the existing ordinary archive refresh, not a duplicate new export. Evaluation-only normalization produces identified gains; additional submission-side score benefit is not identified. Usable-deliverable/readback rationale is separate. Macro mode0, links mode0, immutable original/isolated copy/force calc/separate hash/errors explicit/no repair/no model; pin/version references and evaluator; no opportunistic reference recalculation. Do not hide regressing or unsupported cases.

Strongest challenge:0 demonstrated primary historical recovery,41 unresolved P1 cases, one harm, severe Template concentration and selected research provenance mean a universal ordinary rebaseline or universal LO semantic-correctness guarantee is not compelled. Evidence supports enforcing the already successful evaluated-cache boundary where research bypassed it, with explicit compatibility/unsupported policies; it does not identify a new architecture benefit or quantify global historic prevalence.

Carry forward Phase12 D — DEMOTE, mechanism and actionability-poor nuisance exactly. Independent post review may challenge this interpretation but cannot rewrite it or primary evidence. No future score-dependent model research before a declared recalc-fair boundary; no automatic historical model reruns or product integration in this phase.
'''
 body+='\n## Separately normalized historical context\n\n'+json.dumps(norm['strata']['P3'],indent=2)+'\n\n## Sole bounded follow-up\n\n'+json.dumps(f,indent=2)+'\n'
 path=OUT/'PRIMARY_ANALYSIS.md';assert not path.exists(),'Frozen primary interpretation already exists';path.write_text(body);(OUT/'PRIMARY_ANALYSIS.sha256').write_text(r.sha(path)+'  PRIMARY_ANALYSIS.md\n')
 names=['PRIMARY_ANALYSIS.md','BASELINE_CORRECTION_LEDGER_RAW.jsonl','BASELINE_CORRECTION_LEDGER.jsonl','SCORE_REPLAY.jsonl','SUMMARY.json','LEDGER_FREEZE.json','HISTORICAL_CLAIM_IMPACT.md','RECALC_FAIR_BASELINE_SPEC.md','STRONG_REVIEW_SURPRISE_RAW.md','STRONG_REVIEW_SURPRISE.md','scoring_recovery/RESULTS.jsonl','scoring_recovery/SUMMARY.json','scoring_recovery/IDENTITY.json','followup_macro_mode/MANIFEST.json','followup_macro_mode/RESULTS.jsonl','followup_macro_mode/SUMMARY.json']
 (OUT/'POST_REVIEW_EVIDENCE_FREEZE.json').write_text(json.dumps({'stage':'complete primary analysis before GateC','hashes':{n:r.sha(OUT/n) for n in names}},indent=2));print('primary interpretation frozen')
if __name__=='__main__':main()
